acme_test:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

blog_list:
    path:     /blog
    defaults: { _controller: AppBundle:Blog:list }

blog_show:
    path:     /blog/{slug}
    defaults: { _controller: AppBundle:Blog:show }

lucky_number:
    path:     /lucky/number
    defaults:  { _controller: AppBundle:Lucky:number}