app:
    resource: '@AppBundle/Controller/'
    type: annotation

get_product:
    path:     /product/{productId}
    defaults: { _controller: AppBundle:Product:get}
    methods: [GET]
    requirements:
        id: '\d+'

add_product:
    path:     /product
    defaults: { _controller: AppBundle:Product:add }

add_product_ft:
    path:     /productft
    defaults: { _controller: AppBundle:Product:addWithFormType }

product_update:
    path:     /product/{productId}
    defaults: { _controller: AppBundle:Product:update}
    methods: [PUT]
    requirements:
        id: '\d+'

product_update_query_param:
    path:     /productqp/{productId}
    defaults: { _controller: AppBundle:Product:updateWithQueryParam}
    methods: [PUT]
    requirements:
        productId: '\d+'

product_delete:
    path:     /product/{productId}
    defaults: { _controller: AppBundle:Product:delete}
    methods: [DELETE]
    requirements:
        id: '\d+'

user_add:
    path: /user
    defaults: { _controller: AppBundle:User:add}
    methods: [GET,POST]