app:
    resource: '@AppBundle/Controller/'
    type: annotation

blog_list:
    path:     /blog
    defaults: { _controller: AppBundle:Blog:list }

product_add:
    path:     /product
    defaults: { _controller: AppBundle:Default:create }

product_add_ft:
    path:     /productft
    defaults: { _controller: AppBundle:Default:createFT }

product_show:
    path:     /product/{productId}
    defaults: { _controller: AppBundle:ShowProduct:show}
    methods: [GET]
    requirements:
        id: '\d+'

product_update:
    path:     /product/{productId}
    defaults: { _controller: AppBundle:ShowProduct:update}
    methods: [PUT]
    requirements:
        id: '\d+'

product_update_query_param:
    path:     /productqp/{productId}
    defaults: { _controller: AppBundle:ShowProduct:updateWithQueryParam}
    methods: [PUT]
    requirements:
        productId: '\d+'

product_delete:
    path:     /product/{productId}
    defaults: { _controller: AppBundle:DeleteProduct:deleteproduct}
    methods: [DELETE]
    requirements:
        id: '\d+'

lucky_number:
    path:     /lucky/number
    defaults:  { _controller: AppBundle:Lucky:number}

add_user:
    path: /user
    defaults: { _controller: AppBundle:User:add}
    methods: [GET,POST]